#!/usr/bin/env bash

# Modified version of [Sindre Sorhus's gist](https://gist.github.com/sindresorhus/7996717),
# to display a warning if necessary.

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

echo $changed_files | grep 'package.json' --quiet && node tools/messages.js dependencies-changed
