language: node_js
node_js:
- '6.3'
before_script: npm run lint
script: npm run build
after_success: bash ./scripts/deploy.sh
env:
    global:
    - ENCRYPTION_LABEL: "0601d1c19287"
    - COMMIT_AUTHOR_LABEL: "simonadcock2@gmail.com"
